### ISSUE TITLE
Give a shout-out to Andrew and his upcoming catalog

### ISSUE THREAD

**Issue by dfm** [dfm/k2-paper#11]

**Comment by dfm** [comment]
@benmontet and @davidwhogg: thoughts on this?

I have some words in the discussion but I'm not quite sure what the best way to incorporate this and the fact that we have discussed specific candidates with him.

Another option is to say more in the acknowledgements section.

**Comment by benmontet** [comment]
I don't have strong thoughts. 

We cite his papers already, and we mention private communication at one point. It's not going to count as a citation for him, so there's no immediate direct benefit on his end. I think what we have is appropriate currently.

**Comment by davidwhogg** [comment]
It is just CRITICAL that he not feel ripped off.
