### ISSUE TITLE
too much first person?

### ISSUE THREAD

**Issue by davidwhogg** [dfm/k2-paper#13]
This is a subtle one, and I am not fixing it right now, but the paper has lots of "we did this" and "we do that" and "our" and so on.  My advisor Neugebauer used to say:  Write about the data and the results, not yourself, and only use first person when you want to make a point that requires emphasis or editorializing.  That advice is tough to follow but right now we might be too far on the other side.

**Comment by dfm** [comment]
I agree with your assessment and I've tried to refactor a bit. It still might be too much about "us" but it _is_ an astronomy paper after all...

"we did this stupid hack. then this one. we got some thingz."
