### ISSUE TITLE
EPIC naming

### ISSUE THREAD

**Issue by davidwhogg** [dfm/k2-paper#14]
Does the "EPIC" naming have to be defined somewhere or explained?

**Comment by davidwhogg** [comment]
ps. is there a reference for the EPIC catalog and is it cited?

**Comment by benmontet** [comment]
There is a document from STSCI, but nothing citable. Convention is to include this document as a footnote (which I did at the first direct mention of the EPIC, not including "EPIC 20NNNNNN."
