### ISSUE TITLE
K2 paper out tonight

### ISSUE THREAD

**Issue by benmontet** [dfm/k2-paper#15]
Need to crosscheck EB (and planet…) list against http://arxiv.org/abs/1502.04004

**Comment by dfm** [comment]
I was just looking at that too...

Well all of our measly list of EBs are are in their list. They also include a few of our planet candidates (including the planets from Crossfields paper) :-/

**Comment by dfm** [comment]
They classify the Ian's planets as EBs and about 2/3 of our largest planet candidates.

**Comment by benmontet** [comment]
In that case maybe we should just dump the EBs for this paper (acknowledging other groups are strictly focused on the EB question) and make sure our planet candidate definition (arbitrary depths, no secondaries) is clearly defined. Then we can note that some of ours are included in their list, but we wouldn't expect them to be mutually exclusive because of our differing definitions. Does that sound reasonable to you?

I wonder how @davidwhogg feels.

**Comment by dfm** [comment]
That's fine with me. That paper is a bit obnoxious... I could just run FFTs on all the light curves and call everything binaries too...

**Comment by benmontet** [comment]
Welcome to stellar astronomy!

**Comment by dfm** [comment]
Barf. Anyways. Guess I really gotta finish our paper tonight now!

**Comment by benmontet** [comment]
Let me know if there's anything you want from me.

**Comment by dfm** [comment]
I think that all that is left is captions and a few to dos in the discussion. If you feel like giving a last read through and letting me know if there's anything horrifyingly wrong that would be great!

**Comment by benmontet** [comment]
Points to you for a task I can go do while sitting on the couch.

**Comment by davidwhogg** [comment]
be careful criticizing papers in github issues!  But I agree with the dropping of EBs and we should probably cite this paper.  I sign off on the paper.  Let me know if there is any last thing you need from me; for now I will just go through the text superficially as far as I can before I fall asleep (have you seen my instagram feed for tonight?)

**Comment by dfm** [comment]
I know... the public life is _hard_, isn't it! I've just been working too long on my hand-crafted artisanal catalog of exoplanets to stand by while someone calls them all eclipsing binaries!

**Comment by davidwhogg** [comment]
I know.  Stay strong.  Just cite them and say why you take them to be exoplanets.

**Comment by dfm** [comment]
Done and done.
