### ISSUE TITLE
is figure 4 really a periodogram?

### ISSUE THREAD

**Issue by davidwhogg** [dfm/k2-paper#17]
if it is our own breed of periodogram, give it a "name" that we can use to distinguish it from the square of the FT.

**Comment by dfm** [comment]
Sure. Thoughts?

**Comment by davidwhogg** [comment]
TICogram?  Period-search scalar?  depthogram?

**Comment by dfm** [comment]
You're fired.

**Comment by dfm** [comment]
I'm calling it a "spectrum". I don't think it really needs a name. Much less those ones that you're suggesting :-P

**Comment by davidwhogg** [comment]
Yeah I SUCK!  But I was just saying not "periodogram" because then a skimmer might think we searched by taking a FFT!!!
