### ISSUE TITLE
table 2 positions or ids?

### ISSUE THREAD

**Issue by davidwhogg** [dfm/k2-paper#19]
You use EPIC ids in table 2.  EPIC might be a moving target and/or have bad provenance?  If so, should we also put in RA, Dec values in J2000?  I am concerned about long-term usability.  Or at least we should preserve the EPIC catalog somewhere with our figshares...  And say we did in the paper!

**Comment by dfm** [comment]
I'm happy to include coordinates but I feel like there are much more qualified people responsible for preserving the EPIC (e.g. MAST).

**Comment by davidwhogg** [comment]
I think we should add RA and Dec just for completeness.  Just pull from the EPIC catalog, say in the caption that the RA and Dec are taken _directly_ from the EPIC catalog, get Montet to check that you haven't messed them up, and be sure to say the _epoch_ of the coords (J2000?).

**Comment by davidwhogg** [comment]
Oh and for @adrn's sanity, give them in decimal (not hexagesimal) with enough digits of accuracy to get to 0.1 arcsec or better

**Comment by benmontet** [comment]
RA and Dec are a good thing. People are lazy.

They will be J2000 from the EPIC, and you should note that the EPIC also
includes proper motion information (although it doesn't need to go into the
table, I think).

It doesn't really matter but (see point above) I think they should be in
hh:mm:ss.s +dd:mm:ss.s format, not the fractional degrees that the EPIC
has. Astropy among others will do the conversion.

**Comment by benmontet** [comment]
Oh, disagreement!

Decimal is fine too, I suppose, having them there is the important thing.

**Comment by dfm** [comment]
@benmontet: Any chance you would be willing to make that list in whatever format you like?

**Comment by benmontet** [comment]
Sure.

**Comment by adrn** [comment]
:+1: to decimal

**Comment by benmontet** [comment]
Okay they're in.

**Comment by dfm** [comment]
Great! Thanks.

**Comment by davidwhogg** [comment]
LOVE IT
