### ISSUE TITLE
False positive discussion

### ISSUE THREAD

**Issue by timothydmorton** [dfm/k2-paper#22]
Hi team-- My plan is to work today to put some rough numbers and a bit more meat into the astrophysical false positive section.  Stay tuned.

**Comment by dfm** [comment]
Great! Push and pull frequently.

**Comment by dfm** [comment]
Don't forget to add the reference to the .bib file!

**Comment by benmontet** [comment]
I believe we are all satisfied here?

**Comment by dfm** [comment]
I :heart: it!
