### ISSUE TITLE
Trend-Filtering algorithm Kovacs & Bakos

### ISSUE THREAD

**Issue by timothydmorton** [dfm/k2-paper#25]
Gaspar just mentioned to me that the Trend Filtering Algorithm HATNet uses (http://adsabs.harvard.edu/abs/2005MNRAS.356..557K) uses a lot of the same PCA-like principles of tracking variability of other stars.  Not sure the best place to drop in a reference here would be, but might be appropriate.  He also mentioned that they also fit the noise and transit simultaneously, but I think this may just be in the characterization step rather than in the search (e.g. http://adsabs.harvard.edu/abs/2007ASPC..366..133K)

**Comment by dfm** [comment]
I'm on it. Thanks for this!

**Comment by dfm** [comment]
I added a reference. Hopefully this is sufficient and we can go back and add more discussion in response to referee if we need to.
