### ISSUE TITLE
Comment from Kreidberg

### ISSUE THREAD

**Issue by dfm** [dfm/k2-paper#29]
Include magnitudes in the candidate table for the purposes of follow up.

Don't forget to thank Laura Kreidberg in the acks.

**Comment by benmontet** [comment]
All the magnitudes they'd ever want will be in the followup paper.

**Comment by dfm** [comment]
Excellent :fire:

**Comment by davidwhogg** [comment]
but I agree that we should put at least one representative magnitude in the table in this paper

**Comment by benmontet** [comment]
Let's throw the Kps from the EPIC in there. They are the most relevant, and
go most with the ethos of the paper (check out these candidates we found
with this sweet method)
