### ISSUE TITLE
Referee comment: multis

### ISSUE THREAD

**Issue by dfm** [dfm/k2-paper#32]
> 7) It seems, as it is reported for example at pag. 8, that once the
> authors run the detection algorithm they discard signals with
> substantially varying transit depth. I am wondering if this would not
> somehow decrease the detection of multi-planetary systems.
> Please comment.

I'm not sure what the referee is trying to get at here. @benmontet: do you have any thoughts?

**Comment by benmontet** [comment]
I'm not sure exactly what they mean either. I believe they are trying to get at one of two things. 

1) They fundamentally misunderstand the method. They are imagining that we come up with a list of all transits for a star, listed chronologically, and if there are multiple planets we observe the depths changing from transit to transit, so we throw it out. If they think this, that is dangerous!

2) They might be considering the possibility of overlapping transits, which is on paper a valid concern. These would cause the depths to change. However, they are rare (the probability of an overlap in any transit is ~sum of the durations / the period). Moreover, there is one with overlapping transits, and we find it! So while in theory this might cause us to miss some transits, it looks like its not such a huge concern in reality.

**Comment by dfm** [comment]
Ok. This is good. I can respond to this. Thanks!

**Comment by dfm** [comment]
Done.
